site_name: 26-XII-Museum
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
  font:
    text: Roboto    
extra_css:
  - stylesheets/extra.css
  - "https://unpkg.com/aos@next/dist/aos.css"
docs_dir: content
hooks:
- hooks.py
